### PR TITLE
Fixes #1

### LINKED ISSUE #1: Set up the project with a proper structure, including necessary configuration files and initial setup.
Tasks:
1. Initialize a new Node.js project.
2. Set up Webpack for bundling.
3. Create manifest.json for the Chrome extension.

### PR DESCRIPTION
**Pull request by sakshammaggu**
Issue No.: Fixes #1 

Changes:
1) Initialized the new node.js project
2) set up the webpack for bundling
3) initialized the manifest.json file for chrome extension

### CODE REVIEW

**Comment by NavySaw23** [comment]
Hello Saksham, great job on the code. But there are a few pointers we would like to mention before merging the PR -

- Mention the proper name and description in manifest.json
- Lack of "default_popup" parameter in manifest.json
- Lack of an Assets folder for storing icons
- Update the changelog.md with your changes

please fix these issues and you are good to go

**Comment by sakshammaggu** [comment]
Okay will do the following changes.

**Comment by akanksha2305** [comment]
@sakshammaggu use the name of the project -> descr.ai.be and for description u can take from the readme of the github repo.

**Comment by sakshammaggu** [comment]
@akanksha2305 thank you for clarifying the changes. I want to state that the description of rhe project is missing in the Readme file. So help me with the description. Rest of the  changes I have done.

**Comment by akanksha2305** [comment]
@sakshammaggu it has now been updated on the readme!

**Comment by sakshammaggu** [comment]
@akanksha2305 Updated the changes.

**Comment by akanksha2305** [comment]
@sakshammaggu pr merged. Congratulations on your first commit on this repo!! Hope to see more commits by your side.

**Pull request merged**
