### PR TITLE
fixes: #8 #9 Implement User Authentication_Complete

### PR DESCRIPTION
**Pull request by adx04**
[hi @akanksha2305 i have added the authentication-folder and a walkthrough of the issue in the readme.md file suggest any changes or improvements i need to make if required
thanks!

### CODE REVIEW

**Comment by akanksha2305** [comment]
@adx04 you cannot add and work on issues without consulting the mentors.

**Comment by adx04** [comment]
@akanksha2305 for this one ..how will the points be distributed then
someone commit commit first right?
what should i do now

**Comment by akanksha2305** [comment]
@adx04 which issue are you solving?? 
your points arent distributed because you have to work on the issues given.

**Comment by adx04** [comment]
@akanksha2305 i am solving 
#9 Implement User Authentication

**Comment by akanksha2305** [comment]
@adx04 kindly mention the issue number in your pr request

**Comment by adx04** [comment]
i am considering both the UI and backend (mostly focusing on the UI)

**Comment by akanksha2305** [comment]
@adx04 kindly work on one of them first.

**Comment by akanksha2305** [comment]
@adx04 i reviewed your PR. the sign in with google should be above sign up, please use the logo for google sign in. If possible change the font, and I want the color for the project to be on the darker side!

**Comment by adx04** [comment]
ok @akanksha2305 will work on that.
regards

**Comment by adx04** [comment]
@akanksha2305 should i change the background and theme color to a darker ranger or should it be based on a black theme?

**Comment by akanksha2305** [comment]
@adx04 darker range. 
also please join the discord channel and send your frontend over there, it'll be easier for us to discuss. also kindly check out our logo and add the logo as well and see what colors suit it the best.

**Comment by adx04** [comment]
this is a ss of the same:
is it good or should i change it?
image
@akanksha2305 for any issues with my login i am unable to join the discord server right now but will join it ASAP!

**Comment by adx04** [comment]
hello there @akanksha2305 
these are the SS of the frontend
image

image

due to some login issues on my discord i am unable to join the channel though i will join it ASAP!

**Comment by akanksha2305** [comment]
@adx04 this is great, please just add Google for sign up as well and you are good to go !

**Comment by adx04** [comment]
@akanksha2305 okay!

**Comment by akanksha2305** [comment]
@adx04 just do one small change for me, in the src folder, add this auth folder

**Comment by adx04** [comment]
@akanksha2305 added auth to the src folder

**Comment by akanksha2305** [comment]
@adx04 added.

**Comment by akanksha2305** [comment]
@adx04 we are currently unable to run your PR properly. hence, your score isn't added yet. once the PR is properly reviewed again it will be added

**Comment by adx04** [comment]
@akanksha2305  ok!

**Pull request merged**
